# Generated by Django 6.1 on 2026-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_currency',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos (COP)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='COP', max_length=3),
        ),
    ]
