# Generated by Django 6.1 on 2026-08-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('payment_day', models.IntegerField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_months', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interests', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('esencial', 'Esencial'), ('no_esencial', 'No Esencial'), ('deuda', 'Deuda'), ('ahorro', 'Ahorro')], max_length=20)),
                ('sub_category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodicity', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('objective', models.CharField(max_length=200)),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_time_months', models.IntegerField()),
                ('yield_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_saving', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
