# Generated by Django 6.1 on 2026-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='objective',
        ),
        migrations.AddField(
            model_name='saving',
            name='bank',
            field=models.CharField(default='Banco', max_length=100),
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_type',
            field=models.CharField(default='Ahorro', max_length=200),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_interests',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='total_saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='total_time_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='yield_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
